import "ConfigurationViewModel.idl";

namespace NanaBox
{
    [default_interface]
    runtimeclass BasicConfigurationPage : Windows.UI.Xaml.Controls.Page
    {
        BasicConfigurationPage();

        ConfigurationViewModel ViewModel{ get; };
    }
}
