namespace NanaBox
{    
    [default_interface]
    runtimeclass BooleanToStringConverter : Windows.UI.Xaml.Data.IValueConverter
    {
        BooleanToStringConverter();
        String TrueValue;
        String FalseValue;
    }
}
