import "SelectOption.idl";

namespace NanaBox
{
    [default_interface]
    runtimeclass ComPortsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SelectOption UefiConsoleMode;
        String Com1RedirectPath;
        String Com2RedirectPath;

        Windows.Foundation.Collections.IObservableVector<SelectOption> UefiConsoleModeList {get;};
    }
}
