import "ComPortsViewModel.idl";
import "GpuViewModel.idl";
import "NetworkAdapterViewModel.idl";
import "ScsiDeviceViewModel.idl";
import "SelectOption.idl";

namespace NanaBox
{
    [bindable]
    [default_interface]
    runtimeclass ConfigurationViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Int32 Version{ get; };

        String Name;
        SelectOption GuestType;
        SelectOption ProcessorCount;
        UInt64 MemorySize;
        Boolean ExposeVirtualizationExtensions;

        String GuestStateFile;
        String RuntimeStateFile;
        String SaveStateFile;

        ComPortsViewModel ComPorts {get;};
        GpuViewModel Gpu {get;};
        Windows.Foundation.Collections.IObservableVector<NetworkAdapterViewModel> NetworkAdapters {get;};
        Windows.Foundation.Collections.IObservableVector<ScsiDeviceViewModel> ScsiDevices {get;};

        Windows.Foundation.Collections.IObservableVector<SelectOption> GuestTypeList { get; };
        Windows.Foundation.Collections.IObservableVector<SelectOption> ProcessorCountList { get; };
        
        void AddNetworkAdapter();
        Windows.UI.Xaml.Input.ICommand DeleteNetworkAdapterCommand {get;};

        void AddVirtualDisk();
        void AddVirtualImage();
        Windows.UI.Xaml.Input.ICommand DeleteScsiDeviceCommand {get;};
    }
}
