import "ConfigurationViewModel.idl";

namespace NanaBox
{
    [default_interface]
    runtimeclass ConfigurationWindowControl : Windows.UI.Xaml.Controls.UserControl
    {
        ConfigurationWindowControl();

        ConfigurationViewModel ViewModel;
    }
}
