import "ConfigurationViewModel.idl";

namespace NanaBox
{
    [default_interface]
    runtimeclass GraphicsConfigurationPage : Windows.UI.Xaml.Controls.Page
    {
        GraphicsConfigurationPage();

        ConfigurationViewModel ViewModel{ get; };
    }
}
