import "DelegateTypes.idl";

namespace NanaBox
{
    [default_interface]
    runtimeclass MainWindowControl : Windows.UI.Xaml.Controls.Page
    {
        MainWindowControl();

        event RequestStateChangedDelegate RequestEnhancedSession;
        event RequestStateChangedDelegate RequestPauseVirtualMachine;
    }
}
