import "ConfigurationViewModel.idl";

namespace NanaBox
{
    [bindable]
    [default_interface]
    runtimeclass NetworkConfigurationPage : Windows.UI.Xaml.Controls.Page
    {
        NetworkConfigurationPage();

        ConfigurationViewModel ViewModel{ get; };
    }
}
