namespace NanaBox
{

    [default_interface]
    runtimeclass ScsiDeviceViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Boolean Enabled;
        UInt32 DeviceType;
        String Path;
    }
}
