namespace NanaBox
{    
    [default_interface]
    runtimeclass SelectOption : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        SelectOption(String _name, UInt32 _value);

        String Name;
        UInt32 Value;
    }
}
