import "ConfigurationViewModel.idl";

namespace NanaBox
{
    [default_interface]
    runtimeclass SystemConfigurationPage : Windows.UI.Xaml.Controls.Page
    {
        SystemConfigurationPage();

        ConfigurationViewModel ViewModel{ get; };
        Windows.Foundation.Collections.IVector<IInspectable> AllowedProcessorCount{ get; };

        IInspectable BoxedProcessorCount;
        String UInt32ToString(UInt32 value);        
    }
}
